version: '3.8'

services:
  app:
    image: yobistudio/ablegroup-webhook-logger-app:latest
    container_name: webhook-logger-app-prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    entrypoint: /var/www/docker/entrypoint.sh
    ports:
      - "9000:9000"
    networks:
      - webhook-logger

  nginx:
    image: nginx:1.25-alpine
    container_name: webhook-logger-nginx-prod
    restart: unless-stopped
    depends_on:
      - app
    expose:
      - "80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoapi.rule=Host(`bayarind-dev.ablegroup.id`)"
      - "traefik.http.routers.geoapi.entrypoints=websecure"
      - "traefik.http.routers.geoapi.tls.certresolver=le"
      - "traefik.http.services.geoapi.loadbalancer.server.port=80"
    networks:
      - webhook-logger

  traefik:
    image: traefik:v2.11
    container_name: webhook-logger-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - webhook-logger

networks:
  webhook-logger:
    driver: bridge
